language: ruby
rvm:
  - 2.4

install:
  bundle install

script:
  rake

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_KEY
  target-branch: gh-pages
  verbose: true
  on:
    branch: master
