# Jekyll
exclude: nbproject, README.md, manifest.yml, rakefile.rb
permalink: /:title/
url: http://blog.simplytestable.com

# Site
simplytestable:
    title: Simply Testable Blog
  
# Only First P Plugin
only_first_p:
    show_read_more_link: false