# Jekyll
exclude: [README.md, manifest.yml, rakefile.rb, _drafts, Gemfile, GemFile.lock, node_modules]
permalink: /:title/
url: https://blog.simplytestable.com

name: Simply Testable Blog
description: Figuring out how to automate away the pain of routine front-end web testing; the story behind simplytestable.com.

markdown: kramdown

sass:
  sass_dir: _scss

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

  -
    scope:
      path: "illustrations"
    values:
      layout: "illustration"
      is_illustration: true
